planner_client:
  ros__parameters:
    plan_solver_timeout: 15.0  
planner:
  ros__parameters:
    plan_solver_timeout: 15.0  
    plan_solver_plugins: ["UPF"]
    UPF:
      plugin: "plansys2/UPFPlanSolver"
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
    OPTIC:
      plugin: "plansys2/OPTICPlanSolver"
    LPG:
      plugin: "plansys2/LPGTDPlanSolver"
executor:
  ros__parameters:
    bt_builder_plugin: "SimpleBTBuilder"
    # bt_builder_plugin: "STNBTBuilder"
